
'use server';
/**
 * @fileOverview This file implements a Genkit flow for generating AI-powered smart spending alerts.
 *
 * - getSpendingAlerts - Analyzes expenses and returns specific, actionable alerts.
 * - SpendingAlertsInput - Input schema for the alert generation.
 * - SpendingAlertsOutput - Output schema containing a list of alerts.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AlertSeveritySchema = z.enum(['info', 'warning', 'critical']);

const AlertItemSchema = z.object({
  message: z.string().describe('The alert message in Portuguese (Angola context).'),
  severity: AlertSeveritySchema.describe('The importance level of the alert.'),
  category: z.string().optional().describe('The category ID related to the alert.'),
});

const SpendingAlertsInputSchema = z.object({
  expenses: z.array(z.object({
    date: z.string(),
    category: z.string(),
    amount: z.number(),
    description: z.string(),
  })).describe('List of expenses for analysis.'),
  fixedExpenses: z.array(z.object({
    label: z.string(),
    amount: z.number(),
    dueDay: z.number(),
    isPaid: z.boolean()
  })).optional().describe('List of recurring fixed expenses.'),
  budget: z.number().describe('The total monthly budget.'),
  categories: z.array(z.object({
    id: z.string(),
    label: z.string(),
  })).describe('List of available categories.'),
});

const SpendingAlertsOutputSchema = z.object({
  alerts: z.array(AlertItemSchema).describe('A list of smart alerts generated by the AI.'),
});

export type SpendingAlertsInput = z.infer<typeof SpendingAlertsInputSchema>;
export type SpendingAlertsOutput = z.infer<typeof SpendingAlertsOutputSchema>;

export async function getSpendingAlerts(input: SpendingAlertsInput): Promise<SpendingAlertsOutput> {
  return spendingAlertsFlow(input);
}

const spendingAlertsPrompt = ai.definePrompt({
  name: 'spendingAlertsPrompt',
  input: { schema: SpendingAlertsInputSchema },
  output: { schema: SpendingAlertsOutputSchema },
  prompt: `You are KwanzaKeeper, a smart financial assistant for Angolans. 
Analyze the user's spending data and budget to generate 2 to 4 punchy, specific "Smart Alerts".

Context:
- Total Monthly Budget: {{{budget}}} Kz
- Current Expenses: 
{{#each expenses}}
  - {{{date}}}: {{{description}}} ({{{amount}}} Kz) in category {{{category}}}
{{/each}}

{{#if fixedExpenses}}
- Fixed Commitments:
{{#each fixedExpenses}}
  - {{{label}}}: {{{amount}}} Kz (Due Day: {{{dueDay}}}, Status: {{#if isPaid}}Paid{{else}}UNPAID{{/if}})
{{/each}}
{{/if}}

Categories List:
{{#each categories}}
  - {{{id}}}: {{{label}}}
{{/each}}

Your task:
1. Identify if any category is consuming a large portion of the budget.
2. Identify spikes or anomalies (e.g., spending much more this week than last).
3. Provide helpful warnings if the total budget is being approached too quickly, ESPECIALLY if there are unpaid fixed expenses (like rent or school fees) coming up.
4. If a fixed expense is UNPAID and the due day is close, warn the user about their remaining liquid budget.
5. Keep messages short, direct, and in Portuguese (pt-AO).

Example Alerts:
- "Já gastaste 80% do teu orçamento, e a renda vence em 3 dias. Cuidado!" (Severity: warning)
- "Gastaste 40% mais em táxis esta semana comparado à anterior." (Severity: info)
- "Cuidado: Com este ritmo, vais ultrapassar o orçamento total em 5 dias." (Severity: critical)

Return only the JSON list of alerts.`,
});

const spendingAlertsFlow = ai.defineFlow(
  {
    name: 'spendingAlertsFlow',
    inputSchema: SpendingAlertsInputSchema,
    outputSchema: SpendingAlertsOutputSchema,
  },
  async (input) => {
    const { output } = await spendingAlertsPrompt(input);
    return output!;
  }
);
